# Generated by Django 2.1.7 on 2019-05-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='new title', max_length=100),
            preserve_default=False,
        ),
    ]
